const CatItems = [
  {
    cat: 'Lipstick',
    CatItems: [
      {
        id: '1',
        title: 'Red Beautyful Lipstick',
        image: require('../../assets/images/redLipstic.png'),
        type: 'Brand Name: KISS ',
        price: '570.00',
      },
      {
        id: '2',
        title: 'Rich Care Lipstick',
        image: require('../../assets/images/lipbam.png'),
        type: 'Brand Name:INGLOT ',
        price: '720.00',
      },
      {
        id: '3',
        title: 'Weightless Lipstick',
        image: require('../../assets/images/WeightlessLipstick.png'),
        type: 'Brand Name:kosas',
        price: '650.00',
      },
      {
        id: '4',
        title: 'clipart Marry key Lipstick',
        image: require('../../assets/images/Lipstickmarry.png'),
        type: 'Brand Name:Marry key',
        price: '600.00',
      },
      {
        id: '5',
        title: 'super matte lipstick',
        image: require('../../assets/images/pink.png'),
        type: 'Brand Name:INGLOT',
        price: '450.00',
      },
      {
        id: '6',
        title: 'Dark Shade lipstick',
        image: require('../../assets/images/Dark.png'),
        type: 'Brand Name:POPPY',
        price: '780.00',
      },
    ],
  },
  {
    cat: 'Nail Polish',
    CatItems: [
      {
        id: '1',
        title: 'Light Blue Nail Polish',
        image: require('../../assets/images/blue.png'),
        type: 'Brand Name: COSMOS',
        price: '310.00',
      },
      {
        id: '2',
        title: 'Dark blue Nail Polish',
        image: require('../../assets/images/DB.png'),
        type: 'Brand Name: riviera',
        price: '280.00',
      },
      {
        id: '8',
        title: 'black Nail Polish',
        image: require('../../assets/images/black.png'),
        type: 'Brand Name: picture polish',
        price: '210.00',
      },
      {
        id: '3',
        title: 'dark Red ',
        image: require('../../assets/images/darkRed.png'),
        type: 'Brand Name:FLORA',
        price: '200.00',
      },
      {
        id: '4',
        title: 'Higher Shine nail Polish',
        image: require('../../assets/images/n2.png'),
        type: 'Brand Name: Oribe',
        price: '250.00',
      },
      {
        id: '5',
        title: 'Glitter Shine',
        image: require('../../assets/images/glitter.png'),
        type: 'Brand Name: SOPHI',
        price: '220.00',
      },
      {
        id: '6',
        title: 'Purple Nail Polish',
        image: require('../../assets/images/Purple.png'),
        type: 'Brand Name: SAINT GERMAIN',
        price: '150.00',
      },
      {
        id: '7',
        title: 'light Puple',
        image: require('../../assets/images/lightPuple.png'),
        type: 'Brand Name: INFINITE SHINE',
        price: '280.00',
      },
      {
        id: '9',
        title: 'Salon fomula Cream colour',
        image: require('../../assets/images/cream.png'),
        type: 'Brand Name: Nina',
        price: '150.00',
      },
    ],
  },
  {
    cat: 'Makeup items',
    CatItems: [
      {
        id: '1',
        title: 'Mascara Volume and curl',
        image: require('../../assets/images/mascara.png'),
        type: 'Brand Name: Max Factor',
        price: '600.00',
      },
      {
        id: '2',
        title: 'Eyeshadow Pot Frenzy',
        image: require('../../assets/images/wildeyeshadow.png'),
        type: 'Brand Name: Max Factor',
        price: '750.00',
      },
      {
        id: '3',
        title: 'Make-up mini Kit',
        image: require('../../assets/images/m3.png'),
        type: 'Brand Name:Max Factor',
        price: '1980.00',
      },
      {
        id: '4',
        title: 'Make-up full kit',
        image: require('../../assets/images/m4.png'),
        type: 'Brand Name: mugeek',
        price: '5850.00',
      },
      {
        id: '5',
        title: 'Foundation Cream',
        image: require('../../assets/images/R.png'),
        type: 'Brand Name: Marry Key',
        price: '350.00',
      },
      {
        id: '6',
        title: 'Foundation Cream',
        image: require('../../assets/images/QQQ.png'),
        type: 'Brand Name: NYX',
        price: '400.00',
      },
      {
        id: '7',
        title: 'Beauty Pack',
        image: require('../../assets/images/A.png'),
        type: 'Brand Name:Hybra V',
        price: '5680.00',
      },
    ],
  },
  {
    cat: 'Earrings',
    CatItems: [
      {
        id: '1',
        title: 'Big collect Earrings',
        image: require('../../assets/images/big.jpg'),
        type: 'most beautyful earrings',
        price: '30.00',
      },
      {
        id: '2',
        title: 'Roses Earring',
        image: require('../../assets/images/rE3.jpg'),
        type: 'most beautyful earrings',
        price: '350.00',
      },
      {
        id: '3',
        title: 'baby Roses tessel earrings',
        image: require('../../assets/images/rE2.jpg'),
        type: 'most beautyful earrings',
        price: '570.00',
      },
      {
        id: '4',
        title: 'gold color Pearl Earrings',
        image: require('../../assets/images/E1.png'),
        type: 'most beautyful earrings',
        price: '800.00',
      },
      {
        id: 'baby Roses tessel earrings',
        title: '',
        image: require('../../assets/images/piml.jpg'),
        type: 'Indian look earrings',
        price: '850.00',
      },
      {
        id: '5',
        title: 'Indian style Big Earrings',
        image: require('../../assets/images/E2.png'),
        type: 'Indian look earrings',
        price: '850.00',
      },
      {
        id: '6',
        title: 'Big doubble  flower Earring',
        image: require('../../assets/images/EF.jpg'),
        type: 'beautiful flower earring',
        price: '350.00',
      },
      {
        id: '7',
        title: 'earring Tassel',
        image: require('../../assets/images/earringTassel.png'),
        type: 'hand made earrings',
        price: '500.00',
      },
      {
        id: '8',
        title: 'earring Tassel half Moon',
        image: require('../../assets/images/earring.png'),
        type: 'beautyful earrings',
        price: '450.00',
      },
      {
        id: '9',
        title: 'Roses with peal',
        image: require('../../assets/images/rose.jpg'),
        type: 'Hand Made',
        price: '350.00',
      },
      {
        id: '10',
        title: 'California Gold Earrings  earring',
        image: require('../../assets/images/gold.png'),
        type: 'best California product',
        price: '300.00',
      },
      {
        id: '11',
        title: 'Rose Gold Stud Earrings',
        image: require('../../assets/images/rose.jpg'),
        type: 'best California product',
        price: '280.00',
      },
      {
        id: '12',
        title: 'Purple orcid Earrings',
        image: require('../../assets/images/p.jpg'),
        type: 'best California product',
        price: '280.00',
      },

    ],
  },
  {
    cat: 'Wallets',
    CatItems: [
      {
        id: '1',
        title: 'Small hand Wallet',
        image: require('../../assets/images/w1.png'),
        type: 'Leather Wallet',
        price: '600.00',
      },
      {
        id: '2',
        title: 'Pink hart Wallet ',
        image: require('../../assets/images/w2.png'),
        type: ' hand made high quality',
        price: '450.00',
      },
      {
        id: '3',
        title: 'small cute wallet',
        image: require('../../assets/images/w3.png'),
        type: 'small leather wallet',
        price: '350.00',
      },
      {
        id: '4',
        title: 'Purse With Coin Holder',
        image: require('../../assets/images/w4.jpg'),
        type: 'made in Korea',
        price: '300.00',
      },
      {
        id: '5',
        title: 'Cat Wristlet Trio - 3 Pack, Pink',
        image: require('../../assets/images/w5.jpg'),
        type: 'Ultra cute and trendy pink glitter 3 pack',
        price: '350.00',
      },
      {
        id: '6',
        title: 'Paris Pearl Mini Zip Wallet - Mint',
        image: require('../../assets/images/w6.jpg'),
        type: ' perfect accessory to hold your money!',
        price: '600.00',
      },
      {
        id: '7',
        title: 'Coin Bag Wallet Pouch Purse',
        image: require('../../assets/images/w7.jpeg'),
        type: 'Cute Flamingo PurseSize: 10*8*4.5CM',
        price: '240.00',
      },
    ],
  },
  {
    cat: 'Hair Pins',
    CatItems: [
      {
        id: '1',
        title: 'Pink perl Beautyful Hair pin',
        image: require('../../assets/images/pin.png'),
        type: 'flower with pearl fashinonable hair pin',
        price: '180.00',
      },
      {
        id: '2',
        title: 'small diamond side-clip ',
        image: require('../../assets/images/h2.png'),
        type: ' hand made high quality',
        price: '450.00',
      },
      {
        id: '3',
        title: ' Daliya of Grace Hair clip',
        image: require('../../assets/images/hh.png'),
        type: 'blooming flower side hair clip',
        price: '350.00',
      },
      {
        id: '4',
        title: 'CELESTIAL COMB',
        image: require('../../assets/images/h3.png'),
        type: 'made in Korea',
        price: '150.00',
      },
      {
        id: '5',
        title: 'Fashionable hair clips',
        image: require('../../assets/images/h5.png'),
        type: 'Ultra cute and Korean style hair clips',
        price: '350.00',
      },
      {
        id: '6',
        title: 'cute Hair pin',
        image: require('../../assets/images/h6.png'),
        type: 'most cute korean style',
        price: '80.00',
      },
    ],
  },
];

export default CatItems;
