const CatItems = [
  {
    cat: 'FACE WASH',
    CatItems: [
      {
        id: '1',
        title: 'Purifying Neem face wash',
        image: require('../../assets/icons/acne1.png'),
        type: 'Brand Name: Hemalaya ',
        price: '$170.00',
      },
      {
        id: '2',
        title: 'Tea & Neem face wach',
        image: require('../../assets/icons/af1.png'),
        type: 'Brand Name: The beauty co ',
        price: '$200.00',
      },
      {
        id: '3',
        title: 'Cucamber face Wash',
        image: require('../../assets/icons/oily.png'),
        type: 'Brand Name: Nature secret',
        price: '$300.00',
      },
      {
        id: '4',
        title: 'Peparmint face wash',
        image: require('../../assets/icons/af2.png'),
        type: 'Brand Name:Nature secret ',
        price: '$200.00',
      },
      {
        id: '5',
        title: 'purifying apple Face wash',
        image: require('../../assets/icons/af3.jpeg'),
        type: 'Brand Name: Clean & clear',
        price: '$150.00',
      },
      {
        id: '6',
        title: 'Aloe Vera Face wash',
        image: require('../../assets/icons/df7.png'),
        type: 'Brand Name: Himalaya',
        price: '$250.00',
      },
      {
        id: '7',
        title: 'Turmeric Face wash',
        image: require('../../assets/icons/af5.png'),
        type: 'Brand Name: PONDS',
        price: '$180.00',
      },
    ],
  },
  {
    cat: 'Face Cream',
    CatItems: [
      {
        id: '1',
        title: 'jovees pimple cream',
        image: require('../../assets/icons/ac3.jpg'),
        type: 'Brand Name: Jovees',
        price: '$250.00',
      },
      {
        id: '2',
        title: 'herbals-ance-n-pimple cream',
        image: require('../../assets/icons/ac2.png'),
        type: 'Brand Name: Himalaya',
        price: '$250.00',
      },
      {
        id: '3',
        title: 'beauty enhance  anti  ance cream',
        image: require('../../assets/icons/ac4.jpg'),
        type: 'Brand Name: viana',
        price: '$850.00',
      },
      {
        id: '4',
        title: 'winter green spot correcting anti acne cream',
        image: require('../../assets/icons/ac5.jpg'),
        type: 'Brand Name: biotique',
        price: '$550.00',
      },
      {
        id: '5',
        title: 'Ance control gel ',
        image: require('../../assets/icons/ac6.jpg'),
        type: 'Brand Name: O nelle',
        price: '$480.00',
      },
      {
        id: '6',
        title: 'Chia Seed face cream',
        image: require('../../assets/icons/dc7.jpg'),
        type: 'Brand Name: THE FACE SHOP',
        price: '$350.00',
      },
      {
        id: '7',
        title: 'herbal ance Treatment',
        image: require('../../assets/icons/ac7.png'),
        type: 'Brand Name: BISEKA',
        price: '$375.00',
      },
    ],
  },
  {
    cat: 'Body lotion',
    CatItems: [
      {
        id: '1',
        title: 'Body milk',
        image: require('../../assets/icons/dryb2.png'),
        type: 'Brand Name: Dove',
        price: '$400.00',
      },
      {
        id: '2',
        title: 'Body lotion',
        image: require('../../assets/icons/dryb1.png'),
        type: 'Brand Name: Dove',
        price: '$350.00',
      },
      {
        id: '3',
        title: 'cocoa rediant',
        image: require('../../assets/icons/db3.png'),
        type: 'Brand Name: Vasline',
        price: '$180.00',
      },
      {
        id: '4',
        title: 'aloe soothe',
        image: require('../../assets/icons/db4.png'),
        type: 'Brand Name: Vasline',
        price: '$5850.00',
      },
      {
        id: '5',
        title: 'Rich Nourishing',
        image: require('../../assets/icons/db.png'),
        type: 'Brand Name: NIVEA',
        price: '$350.00',
      },
      {
        id: '6',
        title: 'garnier body lotion',
        image: require('../../assets/icons/db5.jpg'),
        type: 'Brand Name: garnier',
        price: '$400.00',
      },
      {
        id: '7',
        title: 'Shea butter & bee honey body lotion',
        image: require('../../assets/icons/db6.jpg'),
        type: 'Brand Name:O nelle',
        price: '$580.00',
      },
    ],
  },
];

export default CatItems;
