const CatItems = [
  {
    cat: 'FACE WASH',
    CatItems: [
      {
        id: '1',
        title: 'Purifying Neem face wash',
        image: require('../../assets/icons/acne1.png'),
        type: 'Brand Name: Hemalaya ',
        price: '170.00',
      },
      {
        id: '2',
        title: 'Tea & Neem face wach',
        image: require('../../assets/icons/af1.png'),
        type: 'Brand Name: The beauty co ',
        price: '200.00',
      },
      {
        id: '3',
        title: 'Cucamber face Wash',
        image: require('../../assets/icons/oily.png'),
        type: 'Brand Name: Nature secret',
        price: '300.00',
      },
      {
        id: '4',
        title: 'Peparmint face wash',
        image: require('../../assets/icons/af2.png'),
        type: 'Brand Name:Nature secret ',
        price: '200.00',
      },
      {
        id: '5',
        title: 'purifying apple Face wash',
        image: require('../../assets/icons/af3.jpeg'),
        type: 'Brand Name: Clean & clear',
        price: '150.00',
      },
      {
        id: '6',
        title: 'Aloe Vera Face wash',
        image: require('../../assets/icons/df7.png'),
        type: 'Brand Name: Himalaya',
        price: '250.00',
      },
      {
        id: '7',
        title: 'Turmeric Face wash',
        image: require('../../assets/icons/af5.png'),
        type: 'Brand Name: PONDS',
        price: '180.00',
      },
    ],
  },
  {
    cat: 'Face Cream',
    CatItems: [
      {
        id: '1',
        title: 'jovees pimple cream',
        image: require('../../assets/icons/ac3.jpg'),
        type: 'Brand Name: Jovees',
        price: '250.00',
      },
      {
        id: '2',
        title: 'herbals-ance-n-pimple cream',
        image: require('../../assets/icons/ac2.png'),
        type: 'Brand Name: Himalaya',
        price: '250.00',
      },
      {
        id: '3',
        title: 'beauty enhance  anti  ance cream',
        image: require('../../assets/icons/ac4.jpg'),
        type: 'Brand Name: viana',
        price: '850.00',
      },
      {
        id: '4',
        title: 'winter green spot correcting anti acne cream',
        image: require('../../assets/icons/ac5.jpg'),
        type: 'Brand Name: biotique',
        price: '550.00',
      },
      {
        id: '5',
        title: 'Ance control gel ',
        image: require('../../assets/icons/ac6.jpg'),
        type: 'Brand Name: O nelle',
        price: '480.00',
      },
      {
        id: '6',
        title: 'Chia Seed face cream',
        image: require('../../assets/icons/dc7.jpg'),
        type: 'Brand Name: THE FACE SHOP',
        price: '350.00',
      },
      {
        id: '7',
        title: 'herbal ance Treatment',
        image: require('../../assets/icons/ac7.png'),
        type: 'Brand Name: BISEKA',
        price: '375.00',
      },
    ],
  },
  {
    cat: 'Body lotion',
    CatItems: [
      {
        id: '1',
        title: 'fairness bordy lotion',
        image: require('../../assets/icons/ab1.jpg'),
        type: 'Brand Name: ReeBonn',
        price: '400.00',
      },
      {
        id: '2',
        title: 'Repairing Reparatrice Lotion',
        image: require('../../assets/icons/ab4.png'),
        type: 'Brand Name: ST. IVES',
        price: '350.00',
      },
      {
        id: '3',
        title: 'Soothing Apaosant',
        image: require('../../assets/icons/ab3.png'),
        type: 'Brand Name: ST. IVES',
        price: '320.00',
      },
      {
        id: '4',
        title: 'Vanila Moisturizing Lotion',
        image: require('../../assets/icons/b2.png'),
        type: 'Brand Name: Cedar creek',
        price: '250.00',
      },
      {
        id: '5',
        title: 'white Glow',
        image: require('../../assets/icons/ab5.png'),
        type: 'Brand Name: LOTUS',
        price: '350.00',
      },
      {
        id: '6',
        title: 'Shea butter & bee honey body lotion',
        image: require('../../assets/icons/db6.jpg'),
        type: 'Brand Name:O nelle',
        price: '580.00',
      },
    ],
  },
];

export default CatItems;
