const CatItems = [
  {
    cat: 'FACE WASH',
    CatItems: [
      {
        id: '1',
        title: 'refreshing face wash',
        image: require('../../assets/icons/d1.png'),
        type: 'Brand Name: Olay ',
        price: '170.00',
      },
      {
        id: '2',
        title: 'Neem & Turmeric face wach',
        image: require('../../assets/icons/df2.png'),
        type: 'Brand Name: Forever ',
        price: '200.00',
      },
      {
        id: '3',
        title: 'Gold face Wash',
        image: require('../../assets/icons/df3.jpg'),
        type: 'Brand Name:Forever',
        price: '300.00',
      },
      {
        id: '4',
        title: 'Beauty moisture face wash',
        image: require('../../assets/icons/df4.png'),
        type: 'Brand Name: Dove',
        price: '170.00',
      },
      {
        id: '5',
        title: 'Haldi & Chandan Face wash',
        image: require('../../assets/icons/df5.png'),
        type: 'Brand Name: VLCC',
        price: '150.00',
      },
      {
        id: '6',
        title: 'White beauty Face wash',
        image: require('../../assets/icons/df6.png'),
        type: 'Brand Name: PONDS',
        price: '150.00',
      },
      {
        id: '7',
        title: 'Aloe Vera Face wash',
        image: require('../../assets/icons/df7.png'),
        type: 'Brand Name: Himalaya',
        price: '200.00',
      },
      {
        id: '8',
        title: 'Carret face wash',
        image: require('../../assets/icons/Normal&Dryskin.png'),
        type: 'Brand Name: Nature secret',
        price: '280.00',
      },
    ],
  },
  {
    cat: 'Face Cream',
    CatItems: [
      {
        id: '1',
        title: 'Soothing Night cream ',
        image: require('../../assets/icons/dc1.jpeg'),
        type: 'Brand Name: OPTIMALS',
        price: '480.00',
      },
      {
        id: '2',
        title: 'Optimals Night cream',
        image: require('../../assets/icons/dc2.png'),
        type: 'Brand Name: Oriflame',
        price: '550.00',
      },
      {
        id: '3',
        title: 'wild Rose Night Cream',
        image: require('../../assets/icons/dc3.jpg'),
        type: 'Brand Name: Oriflame',
        price: '850.00',
      },
      {
        id: '4',
        title: 'ponds age miracle',
        image: require('../../assets/icons/dc4.png'),
        type: 'Brand Name: PONDS',
        price: '550.00',
      },
      {
        id: '5',
        title: 'virgin coconut face cream ',
        image: require('../../assets/icons/dc5.jpg'),
        type: 'Brand Name: spa ceylon',
        price: '480.00',
      },
      {
        id: '6',
        title: 'ALMOND NOURISHING CREAM',
        image: require('../../assets/icons/dc6.jpg'),
        type: 'Brand Name: aroma magic',
        price: '375.00',
      },
      {
        id: '7',
        title: 'Chia Seed face cream',
        image: require('../../assets/icons/dc7.jpg'),
        type: 'Brand Name: THE FACE SHOP',
        price: '350.00',
      },
    ],
  },
  {
    cat: 'Body lotion',
    CatItems: [
      {
        id: '1',
        title: 'Body milk',
        image: require('../../assets/icons/dryb2.png'),
        type: 'Brand Name: Dove',
        price: '400.00',
      },
      {
        id: '2',
        title: 'Body lotion',
        image: require('../../assets/icons/dryb1.png'),
        type: 'Brand Name: Dove',
        price: '350.00',
      },
      {
        id: '3',
        title: 'cocoa rediant',
        image: require('../../assets/icons/db3.png'),
        type: 'Brand Name: Vasline',
        price: '180.00',
      },
      {
        id: '4',
        title: 'aloe soothe',
        image: require('../../assets/icons/db4.png'),
        type: 'Brand Name: Vasline',
        price: '270.00',
      },
      {
        id: '5',
        title: 'Rich Nourishing',
        image: require('../../assets/icons/db.png'),
        type: 'Brand Name: NIVEA',
        price: '350.00',
      },
      {
        id: '6',
        title: 'garnier body lotion',
        image: require('../../assets/icons/db5.jpg'),
        type: 'Brand Name: garnier',
        price: '400.00',
      },
      {
        id: '7',
        title: 'Shea butter & bee honey body lotion',
        image: require('../../assets/icons/db6.jpg'),
        type: 'Brand Name:O nelle',
        price: '580.00',
      },
    ],
  },
];

export default CatItems;
