const CatItems = [
  {
    cat: 'FACE WASH',
    CatItems: [
      {
        id: '1',
        title: 'Carrot face wash',
        image: require('../../assets/icons/Normal&Dryskin.png'),
        type: 'Brand Name:nature secret ',
        price: '170.00',
      },
      {
        id: '2',
        title: 'Lightning face wash',
        image: require('../../assets/icons/f1.png'),
        type: 'Brand Name: Dremlite ',
        price: '220.00',
      },
      {
        id: '3',
        title: 'Foaming face wash',
        image: require('../../assets/icons/n1.png'),
        type: 'Brand Name:pure & simple',
        price: '650.00',
      },
      {
        id: '4',
        title: 'Purifying Face Wash',
        image: require('../../assets/icons/n2.png'),
        type: 'Brand Name: My Rose',
        price: '600.00',
      },
      {
        id: '5',
        title: 'White beauty pearl face wash',
        image: require('../../assets/icons/n3.png'),
        type: 'Brand Name:PONDS',
        price: '450.00',
      },
      {
        id: '6',
        title: 'Light & radiant face Wash',
        image: require('../../assets/icons/n5.png'),
        type: 'Brand Name: GARNIER',
        price: '$450.00',
      },
      {
        id: '7',
        title: 'GOLD face Wash',
        image: require('../../assets/icons/n6.jpg'),
        type: 'Brand Name: Lia',
        price: '780.00',
      },
      {
        id: '8',
        title: 'TEA TREE OIL face wash',
        image: require('../../assets/icons/n7.png'),
        type: 'Brand Name: Lia',
        price: '780.00',
      },
    ],
  },
  {
    cat: 'Face Cream',
    CatItems: [
      {
        id: '1',
        title: 'Safron face cream',
        image: require('../../assets/icons/c5.png'),
        type: 'Brand Name: ayush',
        price: '200.00',
      },
      {
        id: '2',
        title: 'Fair & natural face cream',
        image: require('../../assets/icons/c6.png'),
        type: 'Brand Name: janet',
        price: '580.00',
      },
      {
        id: '3',
        title: 'GRAPE face cream',
        image: require('../../assets/icons/c1.png'),
        type: 'Brand Name: ORIFLAME',
        price: '870.00',
      },
      {
        id: '4',
        title: 'Day shield',
        image: require('../../assets/icons/c2.png'),
        type: 'Brand Name: ORIFLAME',
        price: '150.00',
      },
      {
        id: '5',
        title: 'Skin youth nigh cream',
        image: require('../../assets/icons/c3.png'),
        type: 'Brand Name:  ORIFLAME',
        price: '500.00',
      },
      {
        id: '6',
        title: 'Moisturising Day Cream',
        image: require('../../assets/icons/c4.png'),
        type: 'Brand Name: ESSENTIALS',
        price: '310.00',
      },
      {
        id: '7',
        title: 'mulberry fairness cream',
        image: require('../../assets/icons/c7.jpg'),
        type: 'Brand Name: Natures Secrets',
        price: '470.00',
      },
    ],
  },
  {
    cat: 'Body lotion',
    CatItems: [
      {
        id: '1',
        title: 'Volare Body Cream',
        image: require('../../assets/icons/b1.png'),
        type: 'Brand Name:  ORIFLAME',
        price: '520.00',
      },
      {
        id: '2',
        title: 'Moisturizing Lotion (Vanilla)',
        image: require('../../assets/icons/b2.png'),
        type: 'Brand Name: cedar creek',
        price: '650.00',
      },
      {
        id: '3',
        title: 'Cocoa butter + body Lotion',
        image: require('../../assets/icons/b3.png'),
        type: 'Brand Name:Max Natures Secrets',
        price: '280.00',
      },
      {
        id: '4',
        title: 'Glow perfect Lotion',
        image: require('../../assets/icons/b4.png'),
        type: 'Brand Name: velvet',
        price: '220.00',
      },
      {
        id: '5',
        title: 'Satin Smooth',
        image: require('../../assets/icons/b5.jpg'),
        type: 'Brand Name: Enchanteur',
        price: '350.00',
      },
      {
        id: '6',
        title: 'Charming Satin Smooth',
        image: require('../../assets/icons/b6.png'),
        type: 'Brand Name: Enchanteur',
        price: '350.00',
      },
      {
        id: '7',
        title: 'Jasmine Bordy Lotion',
        image: require('../../assets/icons/b7.png'),
        type: 'Brand Name:Natures Secrets',
        price: '680.00',
      },
    ],
  },
];

export default CatItems;
