const CatItems = [
  {
    cat: 'FACE WASH',
    CatItems: [
      {
        id: '1',
        title: 'Carret face wash',
        image: require('../../assets/icons/Normal&Dryskin.png'),
        type: 'Brand Name:nature secret ',
        price: '$170.00',
      },
      {
        id: '2',
        title: 'Lighning face wach',
        image: require('../../assets/icons/f1.png'),
        type: 'Brand Name: Dremlite ',
        price: '$220.00',
      },
      {
        id: '3',
        title: 'Weightless Lipstick',
        image: require('../../assets/icons/n1.png'),
        type: 'Brand Name:kosas',
        price: '$650.00',
      },
      {
        id: '4',
        title: 'clipart Marry key Lipstick',
        image: require('../../assets/icons/n2.png'),
        type: 'Brand Name:Marry key',
        price: '$600.00',
      },
      {
        id: '5',
        title: 'super matte lipstick',
        image: require('../../assets/icons/n3.png'),
        type: 'Brand Name:INGLOT',
        price: '$450.00',
      },
      {
        id: '6',
        title: 'Dark Shade lipstick',
        image: require('../../assets/icons/n5.png'),
        type: 'Brand Name:POPPY',
        price: '$780.00',
      },
      {
        id: '7',
        title: 'Dark Shade lipstick',
        image: require('../../assets/icons/n6.jpg'),
        type: 'Brand Name:POPPY',
        price: '$780.00',
      },
      {
        id: '8',
        title: 'Dark Shade lipstick',
        image: require('../../assets/icons/n7.png'),
        type: 'Brand Name:POPPY',
        price: '$780.00',
      },
    ],
  },
  {
    cat: 'Face Cream',
    CatItems: [
      {
        id: '1',
        title: 'Hema ',
        image: require('../../assets/icons/c5.png'),
        type: 'Brand Name:FLORA',
        price: '$200.00',
      },
      {
        id: '2',
        title: 'Higher Shine nail Polish',
        image: require('../../assets/icons/c6.png'),
        type: 'Brand Name: Oribe',
        price: '$250.00',
      },
      {
        id: '3',
        title: 'Glitter Shine',
        image: require('../../assets/icons/c1.png'),
        type: 'Brand Name: SOPHI',
        price: '$220.00',
      },
      {
        id: '4',
        title: 'Purple Nail Polish',
        image: require('../../assets/icons/c2.png'),
        type: 'Brand Name: SAINT GERMAIN',
        price: '$150.00',
      },
      {
        id: '5',
        title: 'light Puple',
        image: require('../../assets/icons/c3.png'),
        type: 'Brand Name: INFINITE SHINE',
        price: '$280.00',
      },
      {
        id: '6',
        title: 'black Nail Polish',
        image: require('../../assets/icons/c4.png'),
        type: 'Brand Name: picture polish',
        price: '$210.00',
      },
      {
        id: '7',
        title: 'Salon fomula Cream colour',
        image: require('../../assets/icons/c7.jpg'),
        type: 'Brand Name: Nina',
        price: '$150.00',
      },
    ],
  },
  {
    cat: 'Body lotion',
    CatItems: [
      {
        id: '1',
        title: 'Mascara Volume and curl',
        image: require('../../assets/icons/b1.png'),
        type: 'Brand Name: Max Factor',
        price: '$600.00',
      },
      {
        id: '2',
        title: 'Eyeshadow Pot Frenzy',
        image: require('../../assets/icons/b2.png'),
        type: 'Brand Name: Max Factor',
        price: '$750.00',
      },
      {
        id: '3',
        title: 'Make-up mini Kit',
        image: require('../../assets/icons/b3.png'),
        type: 'Brand Name:Max Factor',
        price: '$1980.00',
      },
      {
        id: '4',
        title: 'Make-up full kit',
        image: require('../../assets/icons/b4.png'),
        type: 'Brand Name: mugeek',
        price: '$5850.00',
      },
      {
        id: '5',
        title: 'Foundation Cream',
        image: require('../../assets/icons/b5.jpg'),
        type: 'Brand Name: Marry Key',
        price: '$350.00',
      },
      {
        id: '6',
        title: 'Foundation Cream',
        image: require('../../assets/icons/b6.png'),
        type: 'Brand Name: NYX',
        price: '$400.00',
      },
      {
        id: '7',
        title: 'Beauty Pack',
        image: require('../../assets/icons/b7.png'),
        type: 'Brand Name:Hybra V',
        price: '$5680.00',
      },
    ],
  },
];

export default CatItems;
